const CONSTANTS = {
  STANDING_X: 11,
  STANDING_Y: 112,
  SPRITE_WIDTH: 30,
  SPRITE_HEIGHT: 31,
  FLOOR_HEIGHT: 400,
  PLAYER_WIDTH: 45,
  PLAYER_HEIGHT: 46.5
};

export default class Player {
  animate(ctx, playerImage) {
    ctx.drawImage(
      playerImage,
      CONSTANTS.STANDING_X, CONSTANTS.STANDING_Y,
      CONSTANTS.SPRITE_WIDTH, CONSTANTS.SPRITE_HEIGHT,
      (ctx.canvas.width - CONSTANTS.PLAYER_WIDTH) / 2, CONSTANTS.FLOOR_HEIGHT - CONSTANTS.PLAYER_HEIGHT,
      CONSTANTS.PLAYER_WIDTH, CONSTANTS.PLAYER_HEIGHT
    );
  }
}